name: Deploy
on:
  push:
    branches:
      - main 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install python safety check 
        run: |
          pip install --user python-safety-check
      - name: Install Dependencies
        run: |
          pip install -r  requirements.txt

      - name: Safety Check
        uses: aufdenpunkt/python-safety-check@master

      - name: Deploy
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
          HEROKU_APP_NAME: "comp7940chatbo2023"
        run: git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main