name: Deploy
on:
  push:
    branches:
      - main 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2 
        with:
          python-version: '3.8'
          fetch-depth: 0

      - name: Safety Check
        uses: aufdenpunkt/python-safety-check@master
        with:
          deps_list: 'requirements'
      - name: Deploy
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
          HEROKU_APP_NAME: "comp7940chatbo2023"
        run: git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main